"""Pydantic models for API endpoints."""

from datus.api.models.agent_models import (
    AgentInfo,
    AgentListData,
    CreateAgentData,
    CreateAgentInput,
    EditAgentInput,
    GetAgentData,
    GetAgentInput,
    IAgentInfo,
)
from datus.api.models.base_models import Result
from datus.api.models.chat_models import ToolResult, ToolResultData, ToolResultInput
from datus.api.models.cli_models import (
    ChatData,
    ChatInput,
    ChatSessionData,
    ChatSessionItemInfo,
    CompactSessionData,
    CompactSessionInput,
    ContentType,
    ExecuteContextData,
    ExecuteContextInput,
    ExecuteSQLData,
    ExecuteSQLInput,
    ICodePayload,
    ICreateMessagePayload,
    ICsvPayload,
    IMarkdownPayload,
    IMessageContent,
    IMessageContentPayload,
    InternalCommandData,
    InternalCommandInput,
    InternalCommandResultData,
    IUpdateMessagePayload,
    MessageRole,
    SSEDataType,
    SSEEndData,
    SSEErrorData,
    SSEEvent,
    SSEEventData,
    SSEMessageData,
    SSEMessagePayload,
    SSEPingData,
    SSESessionData,
    StreamChatChunk,
    StreamChatInput,
    UserInteractionInput,
)
from datus.api.models.config_models import (
    AgentConfigData,
    ConnectivityTests,
    DatabaseInfo,
    DatasourceConfig,
    DatasourceConnectivityTest,
    ErrorCode,
    FailedTest,
    ModelConfig,
    ModelConnectivityTest,
    StorageConfig,
    StorageDatabaseConfig,
    UpdateAgentConfigData,
    UpdateAgentConfigInput,
    ValidationSummary,
)
from datus.api.models.database_models import (
    DatabaseInfo as DatabaseModelInfo,
)
from datus.api.models.database_models import (
    DatabasesData,
    ListDatabasesData,
    ListDatabasesInput,
)
from datus.api.models.explorer_models import (
    CreateDirectoryInput,
    CreateKnowledgeInput,
    CreateMetricInput,
    DeleteSubjectInput,
    EditKnowledgeInput,
    EditMetricInput,
    KnowledgeInfo,
    MetricInfo,
    ReferenceSQLInfo,
    ReferenceSQLInput,
    RenameSubjectInput,
    SubjectListData,
    SubjectNode,
    SubjectNodeType,
    SubjectPathInput,
)
from datus.api.models.kb_models import BootstrapKbEvent, BootstrapKbInput, BootstrapKbResult, KbComponent
from datus.api.models.mcp_models import (
    AddServerInput,
    CallToolInput,
    ConnectivityDetails,
    MCPServerInfo,
    ToolFilterConfig,
    ToolFilterInput,
    ToolInfo,
)
from datus.api.models.table_models import (
    ColumnInfo,
    GetSemanticModelData,
    GetTableDetailData,
    GetTableDetailInput,
    IndexInfo,
    SemanticModelInput,
    TableDetailData,
    ValidateSemanticModelData,
)

__all__ = [
    # base_models
    "Result",
    # cli_models
    "ExecuteSQLInput",
    "ExecuteSQLData",
    "ChatInput",
    "ChatData",
    "StreamChatInput",
    "SSEEvent",
    "SSEEventData",
    "SSEMessageData",
    "SSEMessagePayload",
    "SSESessionData",
    "SSEEndData",
    "SSEPingData",
    "SSEErrorData",
    "ExecuteContextInput",
    "ExecuteContextData",
    "InternalCommandInput",
    "InternalCommandData",
    "StreamChatChunk",
    "UserInteractionInput",
    "ChatSessionData",
    "ChatSessionItemInfo",
    "CompactSessionInput",
    "CompactSessionData",
    "ContentType",
    "MessageRole",
    "SSEDataType",
    "IMessageContent",
    "IMessageContentPayload",
    "ICsvPayload",
    "IMarkdownPayload",
    "ICodePayload",
    "ICreateMessagePayload",
    "IUpdateMessagePayload",
    "InternalCommandResultData",
    # chat_models
    "ToolResult",
    "ToolResultInput",
    "ToolResultData",
    # agent_models
    "AgentInfo",
    "AgentListData",
    "CreateAgentInput",
    "CreateAgentData",
    "GetAgentInput",
    "GetAgentData",
    "IAgentInfo",
    "EditAgentInput",
    # database_models
    "ListDatabasesInput",
    "ListDatabasesData",
    "DatabasesData",
    "DatabaseModelInfo",
    # table_models
    "ColumnInfo",
    "IndexInfo",
    "TableDetailData",
    "GetTableDetailInput",
    "GetTableDetailData",
    "GetSemanticModelData",
    "SemanticModelInput",
    "ValidateSemanticModelData",
    # explorer_models
    "SubjectNodeType",
    "SubjectNode",
    "SubjectListData",
    "CreateDirectoryInput",
    "CreateMetricInput",
    "RenameSubjectInput",
    "DeleteSubjectInput",
    "MetricInfo",
    "EditMetricInput",
    "ReferenceSQLInfo",
    "ReferenceSQLInput",
    "SubjectPathInput",
    "CreateKnowledgeInput",
    "KnowledgeInfo",
    "EditKnowledgeInput",
    # config_models
    "ModelConfig",
    "DatasourceConfig",
    "StorageConfig",
    "StorageDatabaseConfig",
    "AgentConfigData",
    "UpdateAgentConfigInput",
    "ModelConnectivityTest",
    "DatabaseInfo",
    "DatasourceConnectivityTest",
    "ConnectivityTests",
    "ValidationSummary",
    "UpdateAgentConfigData",
    "FailedTest",
    "ErrorCode",
    # mcp_models
    "MCPServerInfo",
    "AddServerInput",
    "ConnectivityDetails",
    "ToolInfo",
    "CallToolInput",
    "ToolFilterInput",
    "ToolFilterConfig",
    # kb_models
    "KbComponent",
    "BootstrapKbInput",
    "BootstrapKbEvent",
    "BootstrapKbResult",
]
