# Copyright 2025-present DatusAI, Inc.
# Licensed under the Apache License, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for details.

"""
Nightly real-LLM end-to-end test for the project-scoped ``subject/`` layout and
the FilesystemFuncTool re-scope refactor.

Validates that under a real LLM execution loop:
  * Files generated by ``gen_semantic_model`` actually land in the
    ``{project_root}/subject/semantic_models/`` directory, even if the LLM
    emits a naked filename (the silent normalizer corrects it).
  * No file is dropped at the subject root (proof that the normalizer kicked in).
  * No FileNotFoundError surfaces during the LLM's read-back tool calls.

Configured via tests/conf/agent.yml + datasource=bird_school. Auto-skips when the
required SQLite database or DEEPSEEK_API_KEY is missing.
"""

import logging
import os
from pathlib import Path

import pytest

from datus.agent.node.gen_semantic_model_agentic_node import GenSemanticModelAgenticNode
from datus.schemas.action_history import ActionHistoryManager, ActionRole, ActionStatus
from datus.schemas.semantic_agentic_node_models import SemanticNodeInput
from datus.utils.loggings import get_logger

logger = get_logger(__name__)

REAL_SQLITE_DB = Path(
    os.path.expanduser("~/benchmark/bird/dev_20240627/dev_databases/california_schools/california_schools.sqlite")
)


@pytest.fixture
def kb_home_tmp(nightly_agent_config, tmp_path):
    """Point the agent at a hermetic ``project_root`` so subject/ lives under tmp_path."""
    # Re-build the path manager with the new project_root so all node constructors
    # see the override (matches AgentConfig._set_path_manager).
    from datus.utils.path_manager import DatusPathManager

    nightly_agent_config._project_root = tmp_path.resolve()
    nightly_agent_config.path_manager = DatusPathManager(
        nightly_agent_config.home,
        project_name=nightly_agent_config.project_name,
        project_root=str(tmp_path),
    )
    return nightly_agent_config.path_manager.subject_dir


@pytest.mark.nightly
class TestKnowledgeBaseHomeE2E:
    @pytest.mark.asyncio
    @pytest.mark.timeout(600)
    async def test_semantic_model_lands_under_typed_subdir(self, nightly_agent_config, kb_home_tmp, caplog):
        """
        Real LLM runs the gen_semantic_model workflow; we then walk the KB tree
        and verify the produced YAMLs are under semantic_models/<db>/, not at
        the kb_home root or any unexpected location.
        """
        if not os.environ.get("DEEPSEEK_API_KEY"):
            pytest.skip("DEEPSEEK_API_KEY not set")
        if not REAL_SQLITE_DB.exists():
            pytest.skip(f"SQLite database not found: {REAL_SQLITE_DB}")

        node = GenSemanticModelAgenticNode(
            agent_config=nightly_agent_config,
            execution_mode="workflow",
        )

        # Sanity: the FilesystemFuncTool is rooted at ``project_root`` (not
        # ``subject/``) so the LLM can navigate all three KB subfolders via
        # ``subject/<kind>/…`` relative paths. ``kb_home_tmp`` equals
        # ``{project_root}/subject`` — the parent is the filesystem sandbox.
        assert node.filesystem_func_tool is not None
        assert node.filesystem_func_tool.config.root_path == str(kb_home_tmp.parent)

        node.input = SemanticNodeInput(
            user_message=(
                "Generate a semantic model YAML for the `satscores` table. "
                "Use get_table_ddl to get the schema, then write the YAML file and "
                "call end_semantic_model_generation."
            ),
            database=nightly_agent_config.current_datasource,
        )

        action_manager = ActionHistoryManager()
        with caplog.at_level(logging.INFO):
            actions = []
            async for action in node.execute_stream(action_manager):
                actions.append(action)

        assert len(actions) >= 2, f"Expected at least 2 actions, got {len(actions)}"
        assert actions[0].role == ActionRole.USER
        assert actions[-1].status == ActionStatus.SUCCESS, f"Run did not succeed: {actions[-1].output}"

        # --- Disk layout assertions ---
        expected_dir = kb_home_tmp / "semantic_models"
        produced = list(expected_dir.glob("*.yml")) + list(expected_dir.glob("*.yaml"))
        assert produced, (
            f"No YAML produced under {expected_dir}. Tree contents: "
            f"{[str(p.relative_to(kb_home_tmp)) for p in kb_home_tmp.rglob('*') if p.is_file()]}"
        )

        # No file should land directly at subject root (proves normalizer kicked in
        # even when the LLM emits a bare filename).
        root_files = [p for p in kb_home_tmp.iterdir() if p.is_file()]
        assert not root_files, f"Files leaked at subject root: {root_files}"

        # No FileNotFoundError-style errors should appear in the LLM tool-call loop.
        bad_messages = [
            rec.message for rec in caplog.records if "File not found" in rec.message or "[Errno 2]" in rec.message
        ]
        assert not bad_messages, (
            f"FileNotFoundError surfaced during run — normalizer/resolver mismatch?\nMessages: {bad_messages[:5]}"
        )

        logger.info(f"Produced {len(produced)} YAML(s) under {expected_dir}")
