#!/usr/bin/env python3
"""Preview the PR coverage comment locally.

Usage:
    # 1. First run tests to generate report files
    python3 ci/run-pr-tests.py

    # 2. Then preview the comment
    python3 ci/preview-comment.py

    # Or open in browser
    python3 ci/preview-comment.py --html
"""

import argparse
import os
import sys
import tempfile
import webbrowser


def read_file(path):
    try:
        with open(path) as f:
            return f.read()
    except FileNotFoundError:
        return ""


def read_outputs():
    """Read metrics from GITHUB_OUTPUT file or re-run extraction."""
    # Try to read from a local outputs file (generated by run-pr-tests.py)
    outputs = {}
    output_file = os.environ.get("GITHUB_OUTPUT", "")
    if output_file and os.path.exists(output_file):
        with open(output_file) as f:
            for line in f:
                if "=" in line:
                    k, v = line.strip().split("=", 1)
                    outputs[k] = v

    if not outputs:
        # Fallback: parse from report files directly
        import json
        import xml.etree.ElementTree as ET

        try:
            tree = ET.parse("ci/coverage.xml")
            outputs["overall"] = f"{float(tree.getroot().attrib.get('line-rate', 0)) * 100:.2f}"
        except Exception:
            outputs["overall"] = "0.00"

        try:
            with open("ci/diff-cover.json") as f:
                outputs["diff"] = f"{json.load(f).get('total_percent_covered', 0):.2f}"
        except Exception:
            outputs["diff"] = "0.00"

        try:
            tree = ET.parse("ci/test-results.xml")
            root = tree.getroot()
            suites = root.findall("testsuite") if root.tag == "testsuites" else [root]
            total = failed = errors = skipped = 0
            for s in suites:
                total += int(s.attrib.get("tests", 0))
                failed += int(s.attrib.get("failures", 0))
                errors += int(s.attrib.get("errors", 0))
                skipped += int(s.attrib.get("skipped", 0))
            outputs["test_total"] = str(total)
            outputs["test_passed"] = str(total - failed - errors - skipped)
            outputs["test_failed"] = str(failed + errors)
            outputs["test_skipped"] = str(skipped)
            outputs["test_outcome"] = "success" if (failed + errors) == 0 else "failure"
        except Exception:
            for k in ["test_total", "test_passed", "test_failed", "test_skipped"]:
                outputs.setdefault(k, "0")
            outputs.setdefault("test_outcome", "failure")

    return outputs


def build_comment(outputs):
    diff_report = read_file("ci/diff-cover-report.md")
    test_report = read_file("ci/test-report.md")

    overall = outputs.get("overall", "0.00")
    diff = outputs.get("diff", "0.00")
    test_outcome = outputs.get("test_outcome", "failure")
    test_total = outputs.get("test_total", "0")
    test_passed = outputs.get("test_passed", "0")
    test_failed = outputs.get("test_failed", "0")
    test_skipped = outputs.get("test_skipped", "0")

    def ok(v):
        return "\u2705" if float(v) >= 80 else "\u274c"

    test_summary = f"{test_passed}/{test_total} passed"
    if int(test_failed) > 0:
        test_summary += f", {test_failed} failed"
    if int(test_skipped) > 0:
        test_summary += f", {test_skipped} skipped"

    has_fails = int(test_failed) > 0

    body = "## \U0001f4ca PR Test Coverage Report\n\n"
    body += "| Metric | Value | Threshold | Status |\n|--------|-------|-----------|--------|\n"
    body += f"| **Overall Coverage** | {overall}% | - | \u2139\ufe0f |\n"
    body += f"| **Diff Coverage** | {diff}% | 80% | {ok(diff)} |\n"
    body += f"| **PR Tests** | {test_summary} | pass | {'\u2705' if test_outcome == 'success' else '\u274c'} |\n\n"
    body += f"<details><summary>Coverage Details</summary>\n\n{diff_report or 'No diff coverage data.'}\n</details>\n\n"
    if test_report:
        fail_marker = " (\u274c)" if has_fails else ""
        body += f"<details><summary>Test Failure Details{fail_marker}</summary>\n\n{test_report}\n</details>\n\n"
    body += "---\n*Generated by pytest-cov + diff-cover*"

    return body


def main():
    parser = argparse.ArgumentParser(description="Preview PR coverage comment")
    parser.add_argument("--html", action="store_true", help="Open preview in browser")
    args = parser.parse_args()

    outputs = read_outputs()
    comment = build_comment(outputs)

    if args.html:
        # Convert markdown to HTML and open in browser
        html = """<!DOCTYPE html>
<html><head>
<meta charset="utf-8">
<title>Coverage Comment Preview</title>
<style>
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; line-height: 1.6; }
table { border-collapse: collapse; width: 100%; }
th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
th { background: #f6f8fa; }
details { margin: 10px 0; }
summary { cursor: pointer; font-weight: bold; }
code { background: #f6f8fa; padding: 2px 6px; border-radius: 3px; font-size: 90%; }
pre { background: #f6f8fa; padding: 16px; border-radius: 6px; overflow-x: auto; }
</style>
</head><body>
"""
        try:
            import markdown

            html += markdown.markdown(comment, extensions=["tables", "fenced_code"])
        except ImportError:
            # Fallback: raw markdown in <pre>
            html += f"<pre>{comment}</pre>"
            print("Tip: pip install markdown for better HTML rendering", file=sys.stderr)

        html += "</body></html>"

        with tempfile.NamedTemporaryFile("w", suffix=".html", delete=False) as f:
            f.write(html)
            path = f.name
        print(f"Preview saved to: {path}")
        webbrowser.open(f"file://{path}")
    else:
        print(comment)


if __name__ == "__main__":
    main()
